### ISSUE TITLE
build failed.

### ISSUE THREAD

**Issue by kietly** [InCadence/coalesce#2]
Please check if this project is buildable outside InCadance. It can't find the required dependency.
Non-resolvable import POM: Could not find artifact com.incadencecorp.unity:unity-bom:pom:0.0.5

**Comment by kietly** [comment]
Never mind. I saw unity project that I have to build.

**Comment by bytemedwb** [comment]
Unity is another project up on guthub that would need to be pulled and compiled:

https://github.com/InCadence/unity

You will also run into issues with Neo4j. Changes to their code were made which have not been contributed back yet.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Dave Boyd<mailto:dboyd@incadencecorp.com>
Sent: Saturday, May 19, 2018 11:06 AM
To: Derek Clemenzi<mailto:dclemenzi@incadencecorp.com>
Subject: Fwd: [InCadence/coalesce] build failed. (#2)


FYI


-------- Forwarded Message --------
Subject:        [InCadence/coalesce] build failed. (#2)
Date:   Sat, 19 May 2018 06:11:47 -0700

**Comment by kietly** [comment]
Another dependency issue. Can't find this artifact anywhere.
Could not resolve dependencies for project com.incadencecorp.coalesce:coalesce-framework-persister-elasticsearch:bundle:0.0.27-SNAPSHOT: Failure to find ironhide:ironhide-client:jar:2.0.4

**Comment by dclemenzi** [comment]
ironhide adds SSL support to ElasticSearch client and is hosted here: 

https://nexus.devforce.io/content/groups/public

**Comment by dclemenzi** [comment]
The repository information has been added to the pom file and committed. However devforce requires an account. We will need to look into how to make this an optional compile dependency or get devforce to make it publicly available. For now if you are unable to request an account, unless you need the ElasticSearch persister, you can comment it out.

**Comment by kietly** [comment]
I would also suggest if you can please push your jars and any dependencies (such as ironhide library) into to public maven repo. This way folks don't have to build this project (took > 1 hour on my macbook air). I can simply specify maven dependencies in my project. Thanks for fast response.

**Comment by dclemenzi** [comment]
We do have a public Nexus here: 

http://incadencenexus.incadencecorp.com:8081/nexus/

which contains all the Coalesce and Unity jars. This is updated through Jenkins on successful builds. External repositories such as DevForce are not mirrored on our public Nexus. However for running within an OSGi container the ironhide dependencies are not OSGi friendly so there is a bundle-ironhide which shades those dependencies and is published on our public Nexus.  

Sorry we should have pointed you to the public Nexus from the start. I was assuming you wanted to build the code base. We will add the repository details to the github homepage.

**Comment by kietly** [comment]
I do want to build it, but it took too long and missing dependency. For now, I am happy to run coalese examples. FYI, I have to include  geomesa repo and InCadence nexus thirdparty to install neo4j 3.0.2-INC to build your coalese examples github.

You could have hosted ironhide in your thirdparty repo unless there is license restriction.

**Comment by dclemenzi** [comment]
We will add the geomesa repo information in the pom file. As for ironhide since its behind a protected Nexus server we want to obtain permission first.
