### ISSUE TITLE
JodaDateTimeHelper will fail to load if the coalesce.properties file does not exist.

### ISSUE THREAD

**Issue by mattdefazio** [InCadence/coalesce#85]
JodaDateTimeHelper will throw a AccessControlException on line 61 If the application does not have permission to create the coalesce.properties file. This prevents JodaDateTimeHelper from being loaded into the classpath and any attempt to use the JodaDateTimeHelper class will result in a NoClassDefFoundException.

**Comment by dclemenzi** [comment]
Is this because of permissions? It should create the file if it does not exists.

**Comment by dclemenzi** [comment]
Instead of throwing an exception it should just return the default values.

**Comment by dclemenzi** [comment]
Another option is to initialize the settings to use a readonly connector: 

```
        FilePropertyConnector connector = new FilePropertyConnector(Paths.get("src", "test", "resources"));
        connector.setReadOnly(true);

        ElasticSearchSettings.setConnector(connector);
        CoalesceSettings.setConnector(connector);
```
You can see this done in several unit test (which is where the above code snippet came from) to prevent the creation of the property files.

**Comment by dclemenzi** [comment]
Commit f7cf238 modified the settings files to not write values if not found. This should resolve this issue as well.
